dist: trusty
sudo: false

git:
   depth: 9999999

language: node_js
node_js:
  - '12.16.3'

addons:
    chrome: stable
  
cache:
  directories:
    - ./node_modules

install:
  - npm install

before_script:
  - npm install -g @angular/cli
  
script:
  - npm run-script build --base-href $base_href 
  
deploy:
    provider: azure_web_apps
    verbose: true
    on:
        develop
